name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          Invoke-WebRequest -Uri https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_extended_0.121.2_Windows-64bit.zip -OutFile hugo.zip
          Expand-Archive -Path hugo.zip -DestinationPath C:\hugo
          [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;C:\hugo", [System.EnvironmentVariableTarget]::Machine)

      - name: Preprocess Articles
        run: |
          git clone https://${{secrets.TOKEN}}@github.com/wushengyouya/hugo-code.git
          New-Item -ItemType Directory -Path hugo-code\content\post
          Get-ChildItem -Directory | Where-Object { $_.Name -ne "hugo-code" } | Copy-Item -Destination hugo-code\content\post -Recurse

      - name: Generate Site
        run: |
          cd hugo-code 
          hugo -D          

      - name: Publish
        run: |
          cd hugo-code\public
          git config --global user.email "1009889421@qq.com"
          git config --global user.name "wushengyouya"
          git config --global init.defaultBranch main
          git init
          git branch -M main
          git add .
          git commit -m "Update Site at $(Get-Date -Format 'yyyyMMdd-HHmmss')"
          git remote add origin https://${{secrets.TOKEN}}@github.com/wushengyouya/wushengyouya.github.io.git
          git push --force -u origin main
