name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # 获取源码的 checkout命令

      - name: Install Hugo
        run: |
          sudo apt update -y
          # wget https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_0.121.2_linux-amd64.deb
          wget https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_extended_0.121.2_linux-amd64.deb
          # sudo dpkg -i hugo_0.121.2_linux-amd64.deb
          sudo dpkg -i hugo_extended_0.121.2_linux-amd64.deb          

      - name: Preprocess Articles
        run: |
          git clone https://${{secrets.TOKEN}}@github.com/wushengyouya/hugo-code.git
          # for i in *.md; do file_basename=$(basename "$i" .md); file_date=$(date -d @$(git log --follow --format=%at --date default "$i" | tail -1) --rfc-3339=seconds | sed 's/ /T/'); metadata="---\ntitle: $file_basename\ndate: $file_date\n---"; firstline=$(head -n 1 "$i"); if [[ $firstline != -* ]]; then sed -i "1 i $metadata" "$i"; fi; done
          mkdir -p hugo-code/content/post
          shopt -s extglob
          cp -r !(hugo-code) hugo-code/content/post         

      - name: Generate Site
        run: |
          cd hugo-code 
          hugo -D          

      - name: Publish
        run: |
          cd hugo-code/public
          git config --global user.email "1009889421@qq.com"
          git config --global user.name "wushengyouya"
          git config --global init.defaultBranch main
          git init
          git branch -M main
          git add .
          git commit -m "Update Site at $(date "+%Y%m%d-%H%M%S")"
          git remote add origin https://${{secrets.TOKEN}}@github.com/wushengyouya/wushengyouya.github.io.git
          git push --force -u origin main          
